In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('endangeredLang.csv')

In [3]:
data.head(n=6)

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
0,1022,South Italian,Italy,ITA,Vulnerable,7500000.0,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,Italy,ITA,Vulnerable,5000000.0,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS",Vulnerable,4800000.0,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."

In [4]:
data['Countries']

0                                                   Italy
1                                                   Italy
2       Germany, Denmark, Netherlands, Poland, Russian...
3       Belarus, Latvia, Lithuania, Poland, Russian Fe...
4                                      Italy, Switzerland
                              ...
2717                                                Japan
2718                                             Colombia
2719                                             Colombia
2720                                      India, Pakistan
2721                                                 Oman
Name: Countries, Length: 2722, dtype: object

In [8]:
df=data[['Countries','Name in English']]

In [9]:
df.head(5)

                                           Countries Name in English
0                                              Italy   South Italian
1                                              Italy        Sicilian
2  Germany, Denmark, Netherlands, Poland, Russian...       Low Saxon
3  Belarus, Latvia, Lithuania, Poland, Russian Fe...      Belarusian
4                                 Italy, Switzerland         Lombard

In [10]:
data[3:10]

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",Vulnerable,4000000.0,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,"Italy, Switzerland","ITA, CHE",Definitely endangered,3500000.0,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...",Definitely endangered,3500000.0,46.3165,22.3681,"many European countries, most densely in East-..."
6,2211,Yiddish (Israel),Israel,ISR,Definitely endangered,3000000.0,32.0833,34.8333,"most speakers now live outside Europe, mainly ..."
7,1586,Gondi,India,IND,Vulnerable,2713790.0,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands","DEU, BEL, NLD",Vulnerable,2600000.0,50.7781,6.0864,Limburg provinces in Belgium and the Netherlan...
9,1943,Quechua of Southern Bolivia,Bolivia (Plurinational State of),BOL,Vulnerable,2300000.0,-18.0675,-65.7641,"Departments of Cochabamba, Chuquisaca, Potosí ..."

In [23]:
data[data['Number of speakers'] < 5000]

,ID,Name in English,Countries,Country codes alpha 3,Degree of endangerment,Number of speakers,Latitude,Longitude,Description of the location
740,1125,Jirel,Nepal,NPL,Definitely endangered,4919.0,27.6419,86.2123,Dolakha district
741,468,Dolgan,Russian Federation,RUS,Definitely endangered,4865.0,71.3851,97.3388,Dudinka and Khatanga counties in former Taymyr...
742,2057,Romani (Colombia),Colombia,COL,Vulnerable,4858.0,NaN,NaN,Se ubican en los departamentos de Atlántico y ...
743,1160,Tsum,Nepal,NPL,Definitely endangered,4786.0,28.4723,85.0080,banks of Shar river
744,993,Northern Tlapanec,Mexico,MEX,Vulnerable,4771.0,17.4203,-98.7814,"Municipality of Zapotitlán Tablas, state of Gu..."
...,...,...,...,...,...,...,...,...,...
2534,131,|'Auni,South Africa,ZAF,Extinct,0.0,-26.0105,20.3630,NaN
2535,136,|Xam,South Africa,ZAF,Extinct,0.0,-32.2853,20.7590,NaN
2536,1443,ǁKu ǁ'e,South Africa,ZAF,Extinct,0.0,-29.9739,27.0812,Border area of Lesotho and South Africa
2537,1445,ǁKx'au,South Africa,ZAF,Extinct,0.0,-32.2896,21.7968,NaN
2538,130,ǁXegwi,South Africa,ZAF,Extinct,0.0,-25.3500,30.9900,"Lake Chrissie, Eastern Transvaal."