In [1]:
import pandas as pd
import numpy as np

In [2]:
s=pd.Series(range(4),index=['d','a','b','c'])

In [3]:
s

d    0
a    1
b    2
c    3
dtype: int64

In [6]:
s.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [7]:
data = pd.read_csv('GlobalFirePower.csv')
data.head(5)

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,1373650,990025,...,224792,13513,587800,17910000,117600,18560000,9826675,19924,12048,41009
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,798527,2572500,...,87157,1218,44600,514800,365500,3745000,17098242,37653,22408,102000
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,2260000,1452500,...,86000,507,161700,983500,3092000,21270000,9596961,14500,22457,110000
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,1362500,2844750,...,63974,346,51000,507000,359100,8721000,3287263,7000,13888,14500
4,France,FRA,5,66836154,30000000,23750000,775000,387635,204000,183635,...,29640,464,35000,5360000,138200,2737000,643801,4853,4072,8501